obstacle_range: 2.5
raytrace_range: 3.0
footprint: [ [0.25, -0.20], [0.25, 0.20], [-0.25, 0.20], [-0.25, -0.20] ]
# robot_radius: 0.4
inflation_radius: 0.3

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: scan_filtered, marking: true, clearing: true}