obstacle_range: 2.5
raytrace_range: 3.0
footprint: [ [0.245, -0.29], [0.245, 0.29], [-0.34, 0.29], [-0.34, -0.29] ]
inflation_radius: 0.3

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: scan_filtered, marking: true, clearing: true}