# Documentation: http://wiki.ros.org/base_local_planner
TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.26
  min_vel_x: -0.26

  max_vel_y: 0.26
  min_vel_y: -0.26

  max_vel_theta: 1.82
  min_vel_theta: -1.82
  min_in_place_vel_theta: 1.0

  acc_lim_x: 0.001
  acc_lim_y: 0.001
  acc_lim_theta: 0.6

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.20
  yaw_goal_tolerance: 0.20

# Differential-drive robot configuration
  holonomic_robot: true
  y_vels: [-0.3, -0.1, 0.1, 0.3]

# Forward Simulation Parameters
  sim_time: 2.0
  vx_samples: 18
  vtheta_samples: 20
  sim_granularity: 0.05
